name: Build Docker Image

on:
  push:
    branches:
      - main
      - Dockerhub-test
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        DOCKERHUB_USERNAME: zibdie
        OFFICIAL_TAG: zibdie/database-operations:latest
        MAIN_REPO_NAME: zibdie/database-operations
        DOCKERFILE_PATH: ./

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: sudo apt-get update && sudo apt-get install -y jq curl

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Retrieve Docker Credentials
        id: retrieve-credentials
        run: |
          echo "Retrieving Docker credentials..."
          response=$(curl -s -X POST "${{ secrets.ENDPOINT_URL }}" \
            -H "Authorization: ${{ secrets.AUTH_TOKEN }}" \
            -H "Content-Type: application/json" \
            -H "User-Agent: ${{ secrets.GH_USER_AGENT }}" \
            -d '{"key_request": ["DOCKERHUB_KEY"]}')
          
          success=$(echo $response | grep -o '"success":true')
          if [ "$success" ]; then
            # Extract the Docker key but don't echo it
            dockerKey=$(echo $response | grep -o '"DOCKERHUB_KEY":"[^"]*' | cut -d'"' -f4)
            # Use GitHub's add-mask to prevent the key from being logged
            echo "::add-mask::$dockerKey"
            # Store securely in a file with restricted permissions
            echo "$dockerKey" > docker-credentials.txt
            chmod 600 docker-credentials.txt
            echo "Done retrieving credentials"
          else
            echo "Failed to retrieve Docker credentials" >&2
            exit 1
          fi

      - name: Log in to Docker Hub
        run: |
          echo "Logging in to Docker Hub..."
          docker_username=${{ env.DOCKERHUB_USERNAME }}
          # Read password from file but don't echo it
          docker_password=$(cat docker-credentials.txt)
          # Use add-mask again for extra security
          echo "::add-mask::$docker_password"
          echo "$docker_password" | docker login -u "$docker_username" --password-stdin

      - name: Read README content for metadata
        id: readme
        run: |
          content=$(cat README.md)
          escaped_content=$(echo "$content" | jq -Rsa .)
          echo "content=$escaped_content" >> $GITHUB_OUTPUT
          # Save raw content for DockerHub description
          echo "$content" > readme_content.md

      - name: Build and push Docker images
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.DOCKERFILE_PATH }}
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.OFFICIAL_TAG }}
          labels: |
            org.opencontainers.image.description=${{ steps.readme.outputs.content }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}

      - name: Prepare DockerHub credentials for description update
        run: |
          # Read password securely
          docker_password=$(cat docker-credentials.txt)
          # Use add-mask to prevent logging
          echo "::add-mask::$docker_password"
          # Set as env var for next step only
          echo "DOCKERHUB_PASSWORD=$docker_password" >> $GITHUB_ENV

      - name: Update repo description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}
          repository: ${{ env.MAIN_REPO_NAME }}
          readme-filepath: ./README.md
          
      - name: Cleanup credentials
        if: always()
        run: |
          if [ -f docker-credentials.txt ]; then
            rm -f docker-credentials.txt
          fi